pm/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView

from rest_framework import routers
from restapi import views

import settings as settings

admin.autodiscover()

router = routers.DefaultRouter()
router.register(r'links', views.LinkViewSet)
router.register(r'projects', views.ProjectViewSet)
router.register(r'tasklists', views.TaskListViewSet)
router.register(r'tasks', views.TaskViewSet)

urlpatterns = patterns('',
    url(r'^$', 'projects.views.index'),
    url(r'^projects/', include('projects.urls')),
    url(r'^api/1.0/', include('api.urls')),
    url(r'^api/2.0/', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^login/$', 'projects.views.ssl_login', name='login_view'),
    url(r'^logout/$', 'django.contrib.auth.views.logout', name='logout_view'),
    url(r'^release-notes/$', TemplateView.as_view(template_name='projects/release_notes.html'), name='release_notes'),
    url('', include('social.apps.django_app.urls', namespace='social')),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projects/urls.py
from django.conf.urls import patterns, url

from projects import views

urlpatterns = patterns('',
	# /projects/
	url(r'^$', views.index, name='index'),
	# /projects/audit/
	url(r'^audit/$', views.audit, name='audit'),
	# /projects/dashboard/
	url(r'^dashboard/$', views.dashboard, name='dashboard'),
	# /projects/comment/markdown/ -- AJAX ONLY --
	url(r'^comment/markdown/$', views.markdown_preview, name='markdown_preview'),
	# /projects/5/
	url(r'^(?P<project_id>\d+)/$', views.project_detail, name='project_detail'),
	# /projects/5/edit/
	url(r'^(?P<project_id>\d+)/edit/$', views.project_edit, name='project_edit'),
	# /projects/5/complete/ -- AJAX ONLY --
	url(r'^(?P<project_id>\d+)/complete/$', views.project_complete, name='project_complete'),
	# /projects/5/start/ -- AJAX ONLY --
	url(r'^(?P<project_id>\d+)/start/$', views.project_start, name='project_start'),
	# /projects/5/archive/ -- AJAX ONLY --
	url(r'^(?P<project_id>\d+)/archive/$', views.project_archive, name='project_archive'),
	# /projects/5/delete/ -- AJAX ONLY --
	url(r'^(?P<project_id>\d+)/delete/$', views.project_delete, name='project_delete'),
	# /projects/5/clone/ 
	url(r'^(?P<project_id>\d+)/clone/$', views.project_clone, name='project_clone'),
	# /projects/add/
	url(r'^add/$', views.project_edit, name='project_add'),
	# /projects/PM/matthew/
	url(r'^PM/(?P<pm_name>[-\w]+)/$', views.project_by_pm, name='project_by_pm'),
	# /projects/AM/matthew/
	url(r'^AM/(?P<am_name>[-\w]+)/$', views.project_by_am, name='project_by_am'),
	# /projects/PM/matthew/tasks/
	url(r'^PM/(?P<pm_name>\w+)/tasks/$', views.tasks_by_pm, name='tasks_by_pm'),
	# /projects/5/all_tasks_to_project_pm/
	url(r'^(?P<project_id>\d+)/all_tasks_to_project_pm/$', views.all_tasks_to_project_pm, name='all_tasks_to_project_pm'),
	# /projects/tasklists/
	url(r'^tasklists/$', views.tasklist_manage, name='tasklist_manage'),
	# /projects/tasklist/5/tasks/
	url(r'^tasklist/(?P<tasklist_id>\d+)/tasks/$', views.tasklist_tasks, name='tasklist_tasks'),
	# /projects/tasklist/5/task/2/
	url(r'^tasklist/(?P<tasklist_id>\d+)/task/(?P<task_id>\d+)/$', views.task_detail, name='task_detail'),
	# /projects/tasklist/5/task_add/
	url(r'^tasklist/(?P<tasklist_id>\d+)/task_add/$', views.task_edit, name='task_add'),
	# /projects/tasklist/5/task/2/edit/
	url(r'^tasklist/(?P<tasklist_id>\d+)/task/(?P<task_id>\d+)/edit/$', views.task_edit, name='task_edit'),
	# /projects/tasklist/5/task/2/complete/ -- AJAX ONLY --
	url(r'^tasklist/(?P<tasklist_id>\d+)/task/(?P<task_id>\d+)/complete/$', views.task_complete, name='task_complete'),
	# /projects/tasklist/5/task/2/delete/ -- AJAX ONLY --
	url(r'^tasklist/(?P<tasklist_id>\d+)/task/(?P<task_id>\d+)/delete/$', views.task_delete, name='task_delete'),
	# /projects/5/tasklists/
	url(r'^(?P<project_id>\d+)/tasklists/$', views.project_tasklists, name='project_tasklists'),
	# /projects/5/tasklist/2/
	url(r'^(?P<project_id>\d+)/tasklist/<?(?P<tasklist_id>\d+)/$', views.tasklist_detail, name='tasklist_detail'),
	# /projects/5/tasklist/2/delete/
	url(r'^(?P<project_id>\d+)/tasklist/<?(?P<tasklist_id>\d+)/delete/$', views.tasklist_delete, name='tasklist_delete'),
	# /projects/5/tasklist_add/
	url(r'^(?P<project_id>\d+)/tasklist_add/$', views.tasklist_edit, name='tasklist_add'),
	# /projects/5/tasklist/add_from_template/
	url(r'^(?P<project_id>\d+)/tasklist/add_from_template/$', views.tasklist_add_from_template, name='tasklist_add_from_template'),
	# /projects/5/tasklist/2/edit/
	url(r'^(?P<project_id>\d+)/tasklist/(?P<tasklist_id>\d+)/edit/$', views.tasklist_edit, name='tasklist_edit'),
	# /projects/5/links/
	url(r'^(?P<project_id>\d+)/links/$', views.project_links, name='project_links'),
	# /project/5/link/2/
	url(r'^(?P<project_id>\d+)/link/(?P<link_id>\d+)/$', views.link_detail, name='link_detail'),
	# /projects/5/link_add/
	url(r'^(?P<project_id>\d+)/link_add/$', views.link_edit, name='link_add'),
	# /projects/5/link/2/edit/
	url(r'^(?P<project_id>\d+)/link/(?P<link_id>\d+)/edit/$', views.link_edit, name='link_edit'),
	# /projects/<object_type>/5/comment/add
	url(r'^(?P<object_type>\w+)/(?P<object_id>\d+)/comment/add/$', views.comment_edit, name='comment_add'),	
	# /projects/<object_type>/5/comment/2/edit
	url(r'^(?P<object_type>\w+)/(?P<object_id>\d+)/comment/(?P<comment_id>\d+)/edit/$', views.comment_edit, name='comment_edit'),
	# /projects/<object_type>/5/comment/2/
	url(r'^(?P<object_type>\w+)/(?P<object_id>\d+)/comment/(?P<comment_id>\d+)/$', views.comment_detail, name='comment_detail'),
	###### placeholder for risk detail
	url(r'^riskdetail/$', views.index, name='risk_detail'),
)

projects/models.py
import datetime
import hashlib
import random
import string

from django.contrib.auth import get_user_model
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils import timezone

class GetOrNoneManager(models.Manager):
	"""
	Adds get_or_none method to objects
	"""
	def get_or_none(self, **kwargs):
		try:
			return self.get(**kwargs)
		except self.model.DoesNotExist:
			return None

class Category(models.Model):
	"""
	The Category that Projects have.
	e.g. "On Hold", "Internal", "Onboarding", etc.
	"""
	name = models.CharField(max_length=30)

	class Meta:
		ordering = ["name"]
		verbose_name_plural = "categories"

	def __unicode__(self):
		return self.name

STATUS_CHOICES = (
	('N', 'Not Started'),
	('I', 'In Progress'),
	('C', 'Complete'),
)

DEFAULT_STATUS_CHOICE = 'N'

HANDOFF_CHOICES = (
	('N', 'No Handoff'),
	('C', 'Cold Handoff'),
	('W', 'Warm Handoff'),
)

HANDOFF_CHOICE_DICT = {
	'N': 'No Handoff',
	'C': 'Cold Handoff',
	'W': 'Warm Handoff',
}

DEFAULT_HANDOFF_CHOICE = 'N'

class Project(models.Model):
	"""
	The actual project.
	"""
	created = models.DateField(auto_now_add=True)
	acctName = models.CharField(max_length=30, default="New Project")
	category = models.ForeignKey(Category)
	PM = models.ForeignKey(User)
	AM = models.CharField(max_length=30, blank=True, null=True)
	startDate = models.DateField(blank=True, null=True)
	endDate = models.DateField(blank=True, null=True)
	completedDate = models.DateField(blank=True, null=True)
	isArchived = models.BooleanField(default=False)
	isDeleted = models.BooleanField(default=False)
	customerLaunchDate = models.DateField(blank=True, null=True)
	status = models.CharField(max_length=1, choices=STATUS_CHOICES, default=DEFAULT_STATUS_CHOICE)
	handoffType = models.CharField(max_length=1, choices=HANDOFF_CHOICES, default=DEFAULT_HANDOFF_CHOICE)
	customerEngaged = models.BooleanField(default=True)
	destPod = models.CharField(max_length=6, blank=True, null=True)

	objects = GetOrNoneManager()

	class Meta:
		ordering = ["acctName"]

	@property
	def lastTicketResponseDate(self):
		"""
		Queries ZenDesk to get the last response date for a ticket with the sitename associated with self.acctName.
		Used to measure customer engagement.
		"""
		return timezone.now()
		# placeholder - today

	@property
	def recentLastTicketResponseDate(self):
		"""
		Returns True if the last ticket response date is within two days ago.
		"""
		return (self.lastTicketResponseDate < (timezone.now() - datetime.timedelta(days=2)))

	@property
	def otherTickets(self):
		"""
		Queries ZenDesk to get the number of tickets the customer has submitted. Generally if the customer is engaging Support
		instead of Onboarding, they should be funneled back into the Onboarding queue.
		"""
		return 2
		# placeholder - the customer has the handoff ticket plus the initial inquiry ticket

	@property
	def riskScore(self):
		"""
		Looks at the following conditions:
		** Customer has not responded to a ticket in the past two days
		** Customer has more than two tickets open in ZenDesk
		** Customer has not provided a launch date
		** Customer is not engaged

		The more conditions are True, the more the customer needs attention

		See http://stackoverflow.com/questions/12765833/ for a code explanation
		"""
		conditions = [
			(self.recentLastTicketResponseDate),
			(self.otherTickets > 2),
			(self.customerLaunchDate is None),
			(self.customerEngaged == False),
		]
		return len(conditions) - sum(bool(x) for x in conditions) # returns 0..n..len(conditions)

	@property
	def numComments(self):
		""" Returns the number of comments on this project. """
		return self.comment_set.all().count()

	def __unicode__(self):
		return "%s (%s)" % (self.acctName, self.category)

class TaskList(models.Model):
	"""
	A list of tasks.
	"""
	created = models.DateField(auto_now_add=True)
	name = models.CharField(max_length=50, default='New Task List')
	description = models.CharField(max_length=200, blank=True, null=True)
	isTemplate = models.BooleanField(default=False)
	project = models.ForeignKey(Project, blank=True, null=True)
	isDeleted = models.BooleanField(default=False)

	def __unicode__(self):
		if self.project:
			return "%s (%s)" % (self.name, self.project)
		else:
			return "%s (Template)" % (self.name)

class Task(models.Model):
	"""
	Tasks for each project.
	"""
	created = models.DateField(auto_now_add=True)
	tasklist = models.ForeignKey(TaskList)
	name = models.CharField(max_length=50, default='New Task')
	PM = models.ForeignKey(User, blank=True, null=True)
	startDate = models.DateField(blank=True, null=True)
	endDate = models.DateField(blank=True, null=True)
	dueDate = models.DateField(blank=True, null=True)
	description = models.TextField(default='New Task')
	completedDate = models.DateField(blank=True, null=True)
	status = models.CharField(max_length=1, choices=STATUS_CHOICES, default=DEFAULT_STATUS_CHOICE)

	def __unicode__(self):
		return "%s (%s)" % (self.name, self.tasklist)

	@property
	def is_past_due(self):
		if self.dueDate:
		    if (not self.isCompleted) and (timezone.now().date() > self.dueDate):
		    	return True
		return False

	@property
	def can_be_completed(self):
		"""
		Returns True if all of the tasks this task depends on are completed.
		"""
		dependencies = self.task_set.all()
		for d in dependencies:
			if not d.dependsOn.status == 'C':
				return False
		return True

	@property
	def has_dependencies(self):
		"""
		Returns True if there are any Dependency.task objects that have this as a key.
		"""
		return (len(Dependency.objects.filter(task=self)) > 0)

	@property
	def numComments(self):
		""" Returns the number of comments on this project. """
		return self.comment_set.all().count()

class Dependency(models.Model):
	"""
	Handles dependencies of tasks.
	"""
	task = models.ForeignKey(Task, related_name="task_set")
	dependsOn = models.ForeignKey(Task, related_name="dependency_set")

	objects = GetOrNoneManager()

	def __unicode__(self):
		return "%s depends on %s" % (self.task.name, self.dependsOn.name)

	class Meta:
		verbose_name_plural = "dependencies"

class Risk(models.Model):
	"""
	Risks associated with the project.
	"""
	created = models.DateField(auto_now_add=True)
	project = models.ForeignKey(Project)
	name = models.CharField(max_length=50)
	probability = models.IntegerField(default=5)
	impact = models.IntegerField(default=5)
	doesImpactCost = models.BooleanField()
	doesImpactSchedule = models.BooleanField()
	doesImpactPerformance = models.BooleanField()
	plan = models.TextField()

	def __unicode__(self):
		return "%s (%s)" % (self.name, self.project)
		
	@property
	def numComments(self):
		""" Returns the number of comments on this project. """
		return self.comment_set.all().count()

class Link(models.Model):
	"""
	Links associated with the project.
	"""
	created = models.DateField(auto_now_add=True)
	project = models.ForeignKey(Project)
	name = models.CharField(max_length=30)
	description = models.CharField(max_length=200, blank=True, null=True)
	code = models.CharField(max_length=255)

	def __unicode__(self):
		return "%s (%s)" % (self.name, self.project)

	@property
	def numComments(self):
		""" Returns the number of comments on this project. """
		return self.comment_set.all().count()

COMMENT_CHOICES = (
	('P', 'Project'),
	('T', 'Task'),
	('R', 'Risk'),
	('L', 'Link'),
)

class Comment(models.Model):
	"""
	Comments can be associated with Projects, Tasks, Risks, or Links.

	NOTE: I'm certain there is a better way to do this association.
	"""
	type_of_comment = models.CharField(max_length=1, choices=COMMENT_CHOICES)
	created = models.DateField(auto_now_add=True)
	description = models.TextField()
	project = models.ForeignKey(Project, blank=True, null=True)
	task = models.ForeignKey(Task, blank=True, null=True)
	risk = models.ForeignKey(Risk, blank=True, null=True)
	link = models.ForeignKey(Link, blank=True, null=True)
	attachment = models.FileField(upload_to='uploads', blank=True, null=True)

	def __unicode__(self):
		if self.type_of_comment == 'P':
			parent_name = self.project
		elif self.type_of_comment == 'T':
			parent_name = self.task
		elif self.type_of_comment == 'L':
			parent_name = self.link
		else:
			parent_name = ''
		return "%s (%s)" % (self.description, parent_name)

projects/forms.py
from django import forms

from projects.models import Category, Project, TaskList, Task, Link, Comment

class ProjectForm(forms.ModelForm):

	def clean_endDate(self):
		"""
		Validates that the end date is not before the start date.
		"""
		if self.cleaned_data['endDate']:
			if self.cleaned_data['startDate']:
				if self.cleaned_data['startDate'] > self.cleaned_data['endDate']:
					raise forms.ValidationError("Start date cannot be after end date.")
		return self.cleaned_data['endDate']

	category = forms.ModelChoiceField(Category.objects.all(), empty_label=None)
		
	startDate = forms.DateField(input_formats=('%m/%d/%Y', '%m-%d-%y',), required=False)
	endDate = forms.DateField(input_formats=('%m/%d/%Y', '%m-%d-%y',), required=False)
	completedDate = forms.DateField(input_formats=('%m/%d/%Y', '%m-%d-%y',), required=False)
	customerLaunchDate = forms.DateField(input_formats=('%m/%d/%Y', '%m-%d-%y',), required=False)

	class Meta:
		model = Project
		exclude = ['created',]

class TaskListForm(forms.ModelForm):

	class Meta:
		model = TaskList
		exclude = ['created', 'project', 'isTemplate', 'isDeleted',]

class TaskForm(forms.ModelForm):

	def clean_endDate(self):
		"""
		Validates that the end date is not before the start date.
		"""
		if self.cleaned_data['endDate']:
			if self.cleaned_data['startDate']:
				if self.cleaned_data['startDate'] > self.cleaned_data['endDate']:
					raise forms.ValidationError("Start date cannot be after end date.")
		return self.cleaned_data['endDate']
		
	startDate = forms.DateField(input_formats=('%m/%d/%Y', '%m-%d-%y',), required=False)
	endDate = forms.DateField(input_formats=('%m/%d/%Y', '%m-%d-%y',), required=False)
	completedDate = forms.DateField(input_formats=('%m/%d/%Y', '%m-%d-%y',), required=False)

	class Meta:
		model = Task

class LinkForm(forms.ModelForm):

	class Meta:
		model = Link
		exclude = ['project',]

class CommentForm(forms.ModelForm):

	def __init__(self, *args, **kwargs):
		parent_object = kwargs.pop('parent_object')
		super(forms.ModelForm, self).__init__(*args, **kwargs)
		self.fields.pop('type_of_comment')
		if parent_object == 'P':
			self.fields.pop('task')
			self.fields.pop('risk')
			self.fields.pop('link')
		if parent_object == 'T':
			self.fields.pop('project')
			self.fields.pop('risk')
			self.fields.pop('link')
		if parent_object == 'R':
			self.fields.pop('project')
			self.fields.pop('task')
			self.fields.pop('link')
		if parent_object == 'L':
			self.fields.pop('project')
			self.fields.pop('task')
			self.fields.pop('risk')

	class Meta:
		model = Comment

projects/templates/projects/comment_edit.html
{% extends 'projects/base_template.html' %}
{% load staticfiles %}
{% load widget_tweaks %}
{% block title %}{{ add_or_edit }} Comment{% endblock %}
{% block projectdetaillink %}{% url 'project_detail' project_id %}{% endblock %}
{% block projectname %}{{ acctName }}{% endblock %}

{% block body %}
<h2>{{ add_or_edit }} Comment</h2>
<div class="row">
<div class="col-sm-6">
<form method="post" action="">{% csrf_token %}
{% if form.non_field_errors %}
<div class="alert alert-danger">
{{ form.non_field_errors }}
</div>
{% endif %}
<div class="helper-text">Comments support <a href="https://daringfireball.net/projects/markdown/basics" target="_blank"><strong>Markdown</strong></a> syntax.</div>
<div class="fieldWrapper form-group">
	{% if form.description.errors %}<div class="alert alert-danger">{{ form.description.errors }}</div>{% endif %}
	{{ form.description|add_class:"form-control" }}
</div>
<div class="fieldWrapper form-group">
	{% if form.attachment.errors %}<div class="alert alert-danger">{{ form.attachment.errors }}</div>{% endif %}
	<label class="" for="id_name">Attachment: (doesn't work yet)</label>{{ form.attachment|add_class:"form-control" }}
</div>

<button class="btn btn-primary" type="submit" value="submit">Submit</button>
</form>
</div>
<div class="col-sm-6">
    <button class="btn btn-info markdown-preview">Preview</button>
    <div class="row">
        <div id="id_markdown_preview"></div>
    </div>
</div>
</div>
{% csrf_token %}
{% endblock %}

{% block body_js %}
<script src="{% static 'projects/js/jquery.cookie.js' %}"></script>
<script type="text/javascript">

    function csrfSafeMethod(method) {
        // these HTTP methods do not require CSRF protection
        return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
    }

    $.ajaxSetup({
        // add the CSRF token to the request header by default for all POST requests
        beforeSend: function(xhr, settings) {
            var csrftoken = $.cookie('csrftoken');
            if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                xhr.setRequestHeader("X-CSRFToken", csrftoken);
            }
        }
    });


    $('.markdown-preview').click(function() {
        var raw = $('#id_description').val()
        $.ajax({
            type: "POST",
            url: "/projects/comment/markdown/",
            data: {"text": raw},
            success: function(result, textStatus, xmlhttprequest) {
                $('#id_markdown_preview').html(unescape(xmlhttprequest.responseText)); 
            }
        });
    });
</script>
{% endblock %}

projects/templates/projects/detail.html
{% extends 'projects/base_template.html' %}
{% load staticfiles %}
{% block projectdetaillink %}#{% endblock %}
{% block title %}Project detail - {{ project.acctName }}{% endblock %}
{% block projectname %}{{ project.acctName }}{% endblock %}

{% block body %}
<h1>{{ project.acctName }}<span><a class="edit-project btn btn-xs btn-info" href="{% url 'project_edit' project.id %}">Edit Project</a></span></h1>
<p><strong>{{ project.category }}</strong></p>
<p>Project Manager: {{ project.PM }}</p>
{% if project.AM %}
<p>Account Manager: {{ project.AM }}</p>
{% endif %}
<p>{{ project.startDate }} - {{ project.endDate }}</p>
<p class="completed">
{% if project.isCompleted %}
Completed on {{ project.completedDate }}
{% else %}
<a id="mark_complete" href="#">Mark project completed</a>
{% endif %}
{% if not project.isArchived %}
<p class="archived">
<a id="archive_project" href="#">Archive project</a>
</p>
{% endif %}
<h3>Tasks</h3>
<ul>
	{% for tasklist in project.tasklist_set.all %}
		<li><a href="{% url 'tasklist_detail' project.id tasklist.id %}">{{ tasklist.name }}</a> <a class="tasklist_edit btn btn-xs btn-info" href="{% url 'tasklist_edit' project.id tasklist.id %}">Edit</a></li>
		{% if tasklist.task_set.all %}
		<ul>
		{% for task in tasklist.task_set.all %}
			{% if not task.isCompleted %}
			<li><a href="{% url 'task_detail' tasklist.id task.id %}">{{ task.name }}, assigned to {{ task.PM }} {% if task.dueDate %}due {{ task.dueDate }}{% else %}with no due date{% endif %}</a> <a class="task_edit btn btn-xs btn-info" href="{% url 'task_edit' tasklist.id task.id %}">Edit</a> <a class="task_complete btn btn-xs btn-warning" id="task_{{ task.id }}" aria-tasklistid="{{ tasklist.id }}" aria-taskid="{{ task.id }}">Done</a></li>
		  	{% endif %}
		{% endfor %}
		</ul>
		{% endif %}
	{% endfor %}
</ul>
<div><button class="btn btn-danger" id="assign_all_tasks">Assign all tasks to project PM</button></div>
<div><a class="btn btn-primary" href="{% url 'tasklist_add' project.id %}">Add tasklist</a>
<a class="btn btn-success" href="{% url 'tasklist_add_from_template' project.id %}">Add tasklist from template</a></div>
<h3>Risks</h3>
<ul>
	{% for risk in project.risk_set.all %}
		<li>{{ risk.name }}</li>
	{% endfor %}
</ul>
<h3>Links</h3>
<ul>
	{% for link in project.link_set.all %} 
		<li><a target="blank" href="{{ link.code }}">{{ link.name }}</a> <a class="link-edit btn btn-xs btn-info" href="{% url 'link_edit' project.id link.id %}">Edit</a> <a class="link-detail btn btn-xs btn-warning" href="{% url 'link_detail' project.id link.id %}">Detail</a></li>
	{% endfor %}
</ul>
<p><a class="btn btn-primary" href="{% url 'link_add' project.id %}">Add link</a></p> 
<h3>Comments</h3>
<ul>
	{% for comment in project.comment_set.all %}
		<li>{{ comment.description }} <a class="btn btn-xs btn-info" href="{% url 'comment_edit' 'project' project.id comment.id %}">Edit</a> <a class="btn btn-xs btn-warning" href="{% url 'comment_detail' 'project' project.id comment.id %}">Detail</a></li>
	{% endfor %}
</ul>
{% csrf_token %}
{% endblock %}

{% block body_js %}
<script src="{% static 'projects/js/jquery.cookie.js' %}"></script>
<script type="text/javascript">
	function csrfSafeMethod(method) {
	    // these HTTP methods do not require CSRF protection
	    return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
	}

	$.ajaxSetup({
		// add the CSRF token to the request header by default for all POST requests
	    beforeSend: function(xhr, settings) {
			var csrftoken = $.cookie('csrftoken');
	        if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
	            xhr.setRequestHeader("X-CSRFToken", csrftoken);
	        }
	    }
	});

	$('#archive_project').click(function() {
		$.ajax({
			type: "POST",
			url: "/projects/{{ project.id }}/archive/",
			success: function(result, textStatus, xmlhttprequest) {
				code = $.parseJSON(xmlhttprequest.responseText).HTTPRESPONSE;
				if (code == 1) {
					$('.archived').html('Project archived.');
				}
			}
		});
	});

	$('#mark_complete').click(function() {
		$.ajax({
			type: "POST",
			url: "/projects/{{ project.id }}/complete/",
			success: function(result, textStatus, xmlhttprequest) {
				code = $.parseJSON(xmlhttprequest.responseText).HTTPRESPONSE;
				if (code == 1) {
					$('.completed').html('Project complete!');
				}
			}
		});
	});

	$('.task_complete').click(function() {
		var tasklistid = $(this).attr('aria-tasklistid');
		var taskid = $(this).attr('aria-taskid');
		$.ajax({
			type: "POST",
			url: "/projects/tasklist/" + tasklistid + "/task/" + taskid + "/complete/",
			success: function(result, textStatus, xmlhttprequest) {
				code = $.parseJSON(xmlhttprequest.responseText).HTTPRESPONSE;
				if (code == 1) {
					$('#task_' + taskid).hide(); // hide Done button
					$(this).parent().addClass('strike'); // strike out text
				}
			}
		});
	});

	$('#assign_all_tasks').click(function() {
		$.ajax({
			type: "POST",
			url: "/projects/{{ project.id }}/all_tasks_to_project_pm/",
			success: function(result, textStatus, xmlhttprequest) {
				code = $.parseJSON(xmlhttprequest.responseText).HTTPRESPONSE;
				if (code == 1) {
					location.reload();
				}
			}
		});
	});

</script>
{% endblock %}

projects/templates/projects/project_tasklists.html
{% extends 'projects/base_template.html' %}
{% block title %}{{ project.acctName }} Task Lists{% endblock %}
 
{% block subnavlinks %}
<li><a href="{% url 'tasklist_add' project.id %}">Add task list</a></li>
{% endblock %}

{% block body %}
<h2>Task Lists for {{ project.acctName }}</h2>
{% if project.tasklist_set.all %}

	{% for tasklist in project.tasklist_set.all %}
		<div class="row">
			<div class="col-sm-3"><strong>{{ tasklist.name }}</strong></div>
			<div class="col-sm-4"><a href="{% url 'task_add' tasklist.id %}" class="btn btn-xs btn-info">Add tasks to this task list</a></div>
		</div>
		{% if tasklist.task_set.all %}
		<ul>
		{% for task in tasklist.task_set.all %}
			<li>{{ task.name }}</li>
		{% endfor %}
		</ul>
		{% endif %}
	{% endfor %}
{% else %}
<p>No tasklists!</p>
{% endif %}

{% endblock %}